# Generated by Django 6.0 on 2025-12-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbal',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='image',
            field=models.ImageField(upload_to='herbals/'),
        ),
    ]
