# Generated by Django 6.0 on 2026-01-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_herbal_is_home_alter_herbal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Buyurtma raqami')),
                ('full_name', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('payment_method', models.CharField(choices=[('cash_pickup', 'Naqd (Olib ketishda)'), ('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum')], default='cash_pickup', max_length=20, verbose_name="To'lov usuli")),
                ('payment_status', models.BooleanField(default=False, verbose_name="To'lov holati")),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami summa')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy summa')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('ready', 'Tayyor'), ('picked_up', 'Olib ketildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='Olib ketish sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha eslatmalar")),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Punkt nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Ish vaqtlari')),
                ('description', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Olib ketish punkti',
                'verbose_name_plural': 'Olib ketish punktlari',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Umumiy narx')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.pickuppoint', verbose_name='Olib ketish punkti'),
        ),
    ]
