# Generated by Django 6.0 on 2026-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_pickuppoint_orderitem_order_pickup_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herbal',
            name='image',
        ),
        migrations.AddField(
            model_name='herbal',
            name='image_name',
            field=models.CharField(blank=True, default='default.jpg', max_length=255),
        ),
    ]
