# Generated by Django 6.0 on 2026-01-18 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_herbal_image_herbal_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='herbal',
            name='image_name',
            field=models.CharField(blank=True, default='default.jpg', help_text='Rasm nomi: zanjabil.jpg, yalpiz.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
