# Generated by Django 6.0 on 2026-01-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_herbal_created_at_alter_herbal_image_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herbal',
            options={'ordering': ['-created_at'], 'verbose_name': "Dorivor o'simlik", 'verbose_name_plural': "Dorivor o'simliklar"},
        ),
        migrations.AddField(
            model_name='herbal',
            name='image',
            field=models.ImageField(blank=True, help_text='Rasmni yuklang (JPG, PNG formatida)', null=True, upload_to='herbals/', verbose_name='Mahsulot rasmi'),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='image_name',
            field=models.CharField(blank=True, help_text='Avvalgi rasmlar uchun', max_length=255, null=True, verbose_name='Eski rasm nomi'),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name="Bosh sahifada ko'rsatish"),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='herbal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx'),
        ),
    ]
