# Generated by Django 6.0 on 2026-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_herbal_options_herbal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_pickup', 'Naqd (Olib ketishda)')], default='cash_pickup', max_length=20, verbose_name="To'lov usuli"),
        ),
    ]
