# Generated by Django 6.0 on 2026-01-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_herbal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbal',
            name='image',
            field=models.ImageField(blank=True, help_text='Rasmni yuklang (JPG, PNG formatida)', null=True, upload_to='images/herbals/', verbose_name='Mahsulot rasmi'),
        ),
    ]
